#!/usr/bin/env python3
"""Merge per-variant fragments into assets/manifest.json (used by nightly CI).

Reads every frag/**/<variant>.json produced by gen_manifest_fragment.py across the
build matrix and writes a single assets/manifest.json that dpack consumes.

Env:
  REPO       owner/repo, e.g. Isaiah-WU/deepmd-dpack
  VERSION    deepmd-kit version (default: read assets/version.txt)
"""
import glob
import json
import os

repo = os.environ.get("REPO", "Isaiah-WU/deepmd-dpack")
version = os.environ.get("VERSION", "").strip()
if not version:
    with open("assets/version.txt", encoding="utf-8") as fh:
        version = fh.read().strip()

# Start from the EXISTING manifest so variants not rebuilt this run are preserved
# (a CPU-only run must not wipe the live cuda129 entry). Then overlay fresh fragments.
variants = {}
try:
    with open("assets/manifest.json", encoding="utf-8") as fh:
        variants = json.load(fh).get("tools", {}).get("dp", {}).get("variants", {})
except (FileNotFoundError, json.JSONDecodeError):
    variants = {}

fresh = 0
fresh_versions = []
for f in sorted(glob.glob("frag/**/*.json", recursive=True)):
    with open(f, encoding="utf-8") as fh:
        frag = json.load(fh)
    variants[frag["variant"]] = frag["entry"]
    if frag["entry"].get("version"):
        fresh_versions.append(frag["entry"]["version"])
    fresh += 1

if fresh == 0:
    raise SystemExit("merge_manifest: no fragments found under frag/")
if not variants:
    raise SystemExit("merge_manifest: no variants to write")

# Top-level version reflects the freshly-built variants, NOT version.txt: the nightly
# build job only writes a fragment for a variant that built + passed the no-GPU smoke
# test, so this never advances manifest.version to a version that wasn't actually published.
if fresh_versions:
    def _vkey(s):
        try:
            from packaging.version import Version
            return Version(s)
        except Exception:
            return s
    version = max(fresh_versions, key=_vkey)

manifest = {
    "repository": f"https://github.com/{repo}",
    "manifest_url": f"https://raw.githubusercontent.com/{repo}/main/assets/manifest.json",
    "_comment": "Auto-generated by .github/workflows/nightly.yml. Do not edit by hand.",
    "tools": {
        "dp": {
            "name": "DeePMD-kit",
            "description": "Deep Potential Molecular Dynamics — neural network interatomic potential",
            "homepage": "https://github.com/deepmodeling/deepmd-kit",
            "version": version,
            "variants": variants,
        }
    },
}

with open("assets/manifest.json", "w", encoding="utf-8") as fh:
    json.dump(manifest, fh, indent=2, ensure_ascii=False)
    fh.write("\n")
print(json.dumps(manifest, indent=2, ensure_ascii=False))
